services:
  - type: web
    name: ats-resume-backend
    runtime: docker
    repo: https://github.com/Saurav-Kalaskar/Resume-Refactor
    plan: starter
    dockerfilePath: ./backend/Dockerfile
    dockerContext: ./backend
    envVars:
      - key: NVIDIA_API_KEY
        sync: false
      - key: NVIDIA_BASE_URL
        value: https://integrate.api.nvidia.com/v1
      - key: DEFAULT_MODEL
        value: meta/llama-3.3-70b-instruct
      - key: MAX_RETRIES
        value: "3"
      - key: MAX_CHARS
        value: "180"
      - key: PDFLATEX_BIN
        value: /usr/bin/pdflatex
    disk:
      name: tmp
      mountPath: /tmp
      sizeGB: 1
